/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crawler;

public class App {

    public String getGreeting() {
        Util util = new Util();
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
