services:
  db:
    image: mongo:6
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - ./mongodata:/data/db
    command: --logpath /dev/null

  frontier-acceptor:
    build: ./frontier-acceptor
    container_name: frontier-acceptor
    restart: always
    ports:
      - "8080:3000"
    networks:
      - app-network
    depends_on:
      - db
    volumes:
      - ./frontier-acceptor/src:/usr/app/src:ro

  crawler:
    build: ./crawler
    container_name: crawler
    networks:
      - app-network
    depends_on:
      - frontier-acceptor

  bert:
    build: ./bert
    container_name: bert
    networks:
      - app-network
    volumes:
      - ./bert/app:/usr/app/app:ro
      - ./bert/out:/usr/app/out:rw
    ports:
      - "8081:5000"
  
  indexer:
    build: ./indexer
    container_name: indexer
    networks:
      - app-network
    depends_on:
      - bert
      - db
    volumes:
      - ./offline-index:/go/src/app/offline-index:rw

networks:
  app-network:
    driver: bridge
