services:
  db:
    image: mongo:lts
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - ./mongodata:/data/db

  frontier-acceptor:
    build: ./frontier-acceptor
    container_name: frontier-acceptor
    restart: always
    ports:
      - "8080:3000"
    command: "yarn start"
    networks:
      - app-network
    depends_on:
      - db

  crawler:
    build: ./crawler
    container_name: crawler
    networks:
      - app-network
    depends_on:
      - frontier-acceptor

networks:
  app-network:
    driver: bridge
