services:
  db:
    image: mongo:6
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - ./mongodata:/data/db
    command: --logpath /dev/null

  frontier-acceptor:
    build: ./frontier-acceptor
    container_name: frontier-acceptor
    restart: always
    ports:
      - "8080:3000"
    networks:
      - app-network
    depends_on:
      - db
    volumes:
      - ./frontier-acceptor/src:/usr/app/src:ro

  crawler:
    build: ./crawler
    container_name: crawler
    networks:
      - app-network
    depends_on:
      - frontier-acceptor

  inverted-index:
    build: ./inverted-index
    container_name: inverted-index
    networks:
      - app-network
    volumes:
      - ./inverted-index/app:/usr/app/app:ro
      - ./inverted-index/out:/usr/app/out:rw
    ports:
      - "8081:5000"

networks:
  app-network:
    driver: bridge
